### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by idchlife** [tunnckoCore/gibon#3]
I'm trying to use it with typescript but I'm kinda new to it. What exactly does default export of gibbon looks like? Is it function?

Not clear what to do with such included module in bundle:

![image](https://cloud.githubusercontent.com/assets/4563032/23171590/ee4216ce-f863-11e6-8322-76fc503becc8.png)

As I can tell, it's just declaring var gibon inside module and not exporting it anywhere, so module just returns empty Object.

**Comment by tunnckoCore** [comment]
@idchlife :+1: need to update the build flow, cuz currently its main export is IIFE (as seen in the sourcemap url)

I'll provide UMD, CJS and ES builds, so users can use what they want.

As about TS, don't know, i'm no using it and don't understand such things. But kinda support and like @sindresorhus's position https://github.com/sindresorhus/ama/issues/439. So it is more likely i don't add TS file here. But PRs for such is welcome too, but someone should maintain it.

**Comment by tunnckoCore** [comment]
Btw UMD bundle is currently available, but for browsers.

What you use? Kinda feel Browserify? That's a bug currently for Browserify users, because they resolves the IIFE, not the UMD/ES.

**Comment by idchlife** [comment]
webpack with ts-loader. I'll think about adding definition to Definetely Typed in spare time

**Comment by tunnckoCore** [comment]
> webpack with ts-loader.

hm.. that's strange than why it resolves the IIFE build, maybe webpack does not understand `pkg.module` field? huh

> I'll think about adding definition to Definetely Typed in spare time

Great to hear and thanks! Ping me when you done the PR there, so i can learn something, haha :)

**Comment by idchlife** [comment]
@tunnckoCore I'm trying to configure webpack so it would use "main" from package.json and not "browser". Somehow it ends up using "browser" script.

What else uses "browser" field in package.json? Browserify? Trying to understand what's going on wrong with my config here...

**Comment by tunnckoCore** [comment]
Damn. That's sad, but yea one more reason why https://github.com/unpkg/unpkg.com/issues/25 is a problem and why I won't use/set `browser` field any more.

Thanks in any way, I'll update the things this night or tomorrow at least.

**Comment by idchlife** [comment]
@tunnckoCore if talking only about webpack - version 2 was recently released. And it has richer resolving functionality than in version 1. So now problem is solved, thank you for thinking about this with me!

![image](https://cloud.githubusercontent.com/assets/4563032/23200097/7e0d1d1a-f8e3-11e6-8621-9667e6f457b7.png)

**Comment by tunnckoCore** [comment]
that is what i was talking about, yea. i was sure it can be fixed outside of gibon
