### ISSUE TITLE
require('gibon') returns an empty object when using webpack

### ISSUE THREAD

**Issue by gibatronic** [tunnckoCore/gibon#6]
There might be a problem with your UMD bundler, requiring `gibon` using `webpack` results in an empty object:

```js
var gibon = require('gibon');

console.log(gibon); // empty object
```

Versions involved:

```
  gibon 0.3.2
   node 7.7.1
    npm 4.3.0
webpack 2.2.1
```

I made a gist with the steps to reproduce it:
[gist.github.com/gibatronic/b4cc95f723712863a8aa31a796b86a0a](gist.github.com/gibatronic/b4cc95f723712863a8aa31a796b86a0a)

**Comment by gibatronic** [comment]
If I explicit require `dist/gibon.umd` it works fine:

```js
var gibon = require('gibon/dist/gibon.umd');

console.log(gibon); // function
```

So, the issue seems to be `require('gibon')` resolving to `dist/gibon.iife.js`

**Comment by tunnckoCore** [comment]
Yea. Build flow isn't correct. I'm going to update that now, cuz I'm in great mood 50+ commits for today ;d

**Comment by gibatronic** [comment]
Interesting, removing `browser` and `module` entries from `package.json` solves the problem... didn't even know `webpack` looked for those fields, since they are not even documented.

**Comment by tunnckoCore** [comment]
Yea, that's the fact that I know. Browser field is very conflicting - with unpkg.com too, see https://github.com/unpkg/unpkg.com/issues/25, and why i considered to not use `pkg.browser` et all.

**Comment by tunnckoCore** [comment]
> didn't even know webpack looked for those fields, since they are not even documented.

i believe that `module` is supported from v2 to resolve es6 modules correctly, but.. don't know, I'm not webpack, nor browserify user.

**Comment by tunnckoCore** [comment]
@gibatronic, Can you try v0.4? I believe that is fixed.

**Comment by gibatronic** [comment]
Not quite there... it works with plain Node `require`.

But if I use `webpack`, it goes after `dist/gibon.es.js` which only works if I have the Babel plug-in to transpile ES6 export...

This looks like a situation that it's just impossible to please everyone.

Your use of the `module` property is correct, I just don't understand why on Earth webpack goes after it. The Node team already said they won't support ES6 modules.

Anyway, your job is done here, thank you!

**Comment by tunnckoCore** [comment]
Yea, absolutely. :D Some ("so awesome and popular") tools are awful.

Don't know what is happening.. I believe Webpack v2 resolves and respects the `module` field, or at least.. it should just resolve the main which is nothing more than regular nodejs commonjs module... damn tooling. :D

**Comment by gibatronic** [comment]
In [this crowded issue](https://github.com/webpack/webpack/issues/1979) they discuss about it, and they mention this workaround several times: [resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolve-mainfields).

For now, this seems to be the best we can get. We're living a moment of transition, and I'm eager for it to finish.

**Comment by tunnckoCore** [comment]
Ooh, yea yea, I always forget about that issue and the `resolve.mainFields` ;d
